kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ibm-flink-pipeline-pvc.yaml
  namespace: event-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-cephfs