apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-flink-deployment-secret
  namespace: openshift-pipelines
spec:
  params:
    - name: secret-name
      description: The name of the Kubernetes secret to create
      type: string
    - name: secret-namespace
      description: The namespace in which to create the Kubernetes secret
      type: string
  workspaces:
    - name: source
  steps:
    - name: create-secret
      image: bitnami/kubectl:latest
      securityContext:
        runAsUser: 1000
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.source.path)

        echo "Creating Kubernetes Secret $(params.secret-name) in namespace $(params.secret-namespace)..."

        kubectl create secret generic $(params.secret-name) \
          --from-file=flow.json=flow.json \
          --from-file=config.yaml=config-with-creds.yaml \
          --dry-run=client -o yaml \
          --namespace=$(params.secret-namespace) | kubectl apply -n $(params.secret-namespace) -f -

        echo "Secret $(params.secret-name) created successfully in namespace $(params.secret-namespace)."
