apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: set-flink-credentials
  namespace: openshift-pipelines
spec:
  params:
    - name: kafka-username
      type: string
    - name: kafka-password
      type: string
  workspaces:
    - name: source
  steps:
    - name: render-template
      image: registry.access.redhat.com/ubi8/ubi-minimal
      securityContext:
        runAsUser: 1000
      script: |
        #!/bin/sh
        set -e

        cd $(workspaces.source.path)

        sed "s|<username_redacted>|$(params.kafka-username)|g" config.yaml | \
        sed "s|<password_redacted>|$(params.kafka-password)|g" > config-with-creds.yaml

        echo "Rendered config-with-creds.yaml:"
        cat config-with-creds.yaml
